name: Build
on: [push]
jobs:
  setup:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build image
        run: docker build . -t api
#        run: pip install -r requi rements.txt; pip show httpx; pip install -r requirements-dev.txt
#
      - name: Run the container and check that the program launches successfully
        run: timeout --preserve-status docker-compose up --exit-code-from api

  style:
    needs: setup
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Black files
        run: export PATH=/usr/bin/python:$PATH; pip show httpx; python -m black . --check

      - name: Check style
        run: python -m pylint *.py
