name: Build
on: [push]
jobs:
  setup:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: pip install -r requirements.txt --user
      - name: Start app (without api key)
        run: python main.py

  style:
    needs: setup
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Black files
        run: pip install -r requirements.txt; pip install black; python -m black . --check

      - name: Check style
        run: pip install pylint; python -m pylint *.py
